// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/shop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{0}
}

type Bicycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bicycle) Reset() {
	*x = Bicycle{}
	mi := &file_api_proto_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bicycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bicycle) ProtoMessage() {}

func (x *Bicycle) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bicycle.ProtoReflect.Descriptor instead.
func (*Bicycle) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{1}
}

func (x *Bicycle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bicycle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bicycle) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bicycle) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bicycle) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type ListBicyclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBicyclesRequest) Reset() {
	*x = ListBicyclesRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBicyclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBicyclesRequest) ProtoMessage() {}

func (x *ListBicyclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBicyclesRequest.ProtoReflect.Descriptor instead.
func (*ListBicyclesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{2}
}

type ListBicyclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bicycles      []*Bicycle             `protobuf:"bytes,1,rep,name=bicycles,proto3" json:"bicycles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBicyclesResponse) Reset() {
	*x = ListBicyclesResponse{}
	mi := &file_api_proto_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBicyclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBicyclesResponse) ProtoMessage() {}

func (x *ListBicyclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBicyclesResponse.ProtoReflect.Descriptor instead.
func (*ListBicyclesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{3}
}

func (x *ListBicyclesResponse) GetBicycles() []*Bicycle {
	if x != nil {
		return x.Bicycles
	}
	return nil
}

type GetBicycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBicycleRequest) Reset() {
	*x = GetBicycleRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBicycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBicycleRequest) ProtoMessage() {}

func (x *GetBicycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBicycleRequest.ProtoReflect.Descriptor instead.
func (*GetBicycleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{4}
}

func (x *GetBicycleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchBicyclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBicyclesRequest) Reset() {
	*x = SearchBicyclesRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBicyclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBicyclesRequest) ProtoMessage() {}

func (x *SearchBicyclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBicyclesRequest.ProtoReflect.Descriptor instead.
func (*SearchBicyclesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{5}
}

func (x *SearchBicyclesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BicycleId     string                 `protobuf:"bytes,3,opt,name=bicycle_id,json=bicycleId,proto3" json:"bicycle_id,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{6}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetBicycleId() string {
	if x != nil {
		return x.BicycleId
	}
	return ""
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BicycleId     string                 `protobuf:"bytes,3,opt,name=bicycle_id,json=bicycleId,proto3" json:"bicycle_id,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	UserEmail     string                 `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetBicycleId() string {
	if x != nil {
		return x.BicycleId
	}
	return ""
}

func (x *CreateOrderRequest) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CreateOrderRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_api_proto_shop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{11}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Rental struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BicycleId     string                 `protobuf:"bytes,3,opt,name=bicycle_id,json=bicycleId,proto3" json:"bicycle_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rental) Reset() {
	*x = Rental{}
	mi := &file_api_proto_shop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rental) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rental) ProtoMessage() {}

func (x *Rental) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rental.ProtoReflect.Descriptor instead.
func (*Rental) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{12}
}

func (x *Rental) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rental) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Rental) GetBicycleId() string {
	if x != nil {
		return x.BicycleId
	}
	return ""
}

func (x *Rental) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Rental) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Rental) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Rental) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BicycleId     string                 `protobuf:"bytes,2,opt,name=bicycle_id,json=bicycleId,proto3" json:"bicycle_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRentalRequest) Reset() {
	*x = CreateRentalRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRentalRequest) ProtoMessage() {}

func (x *CreateRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRentalRequest.ProtoReflect.Descriptor instead.
func (*CreateRentalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRentalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRentalRequest) GetBicycleId() string {
	if x != nil {
		return x.BicycleId
	}
	return ""
}

func (x *CreateRentalRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateRentalRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateRentalRequest) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type GetRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRentalRequest) Reset() {
	*x = GetRentalRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalRequest) ProtoMessage() {}

func (x *GetRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalRequest.ProtoReflect.Descriptor instead.
func (*GetRentalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{14}
}

func (x *GetRentalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EndRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRentalRequest) Reset() {
	*x = EndRentalRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRentalRequest) ProtoMessage() {}

func (x *EndRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRentalRequest.ProtoReflect.Descriptor instead.
func (*EndRentalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{15}
}

func (x *EndRentalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRentalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRentalsRequest) Reset() {
	*x = ListRentalsRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRentalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRentalsRequest) ProtoMessage() {}

func (x *ListRentalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRentalsRequest.ProtoReflect.Descriptor instead.
func (*ListRentalsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{16}
}

func (x *ListRentalsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListRentalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rentals       []*Rental              `protobuf:"bytes,1,rep,name=rentals,proto3" json:"rentals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRentalsResponse) Reset() {
	*x = ListRentalsResponse{}
	mi := &file_api_proto_shop_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRentalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRentalsResponse) ProtoMessage() {}

func (x *ListRentalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRentalsResponse.ProtoReflect.Descriptor instead.
func (*ListRentalsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{17}
}

func (x *ListRentalsResponse) GetRentals() []*Rental {
	if x != nil {
		return x.Rentals
	}
	return nil
}

type SendOrderConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderConfirmationRequest) Reset() {
	*x = SendOrderConfirmationRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderConfirmationRequest) ProtoMessage() {}

func (x *SendOrderConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendOrderConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{18}
}

func (x *SendOrderConfirmationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendOrderConfirmationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type SendRentalConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	RentalId      string                 `protobuf:"bytes,2,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRentalConfirmationRequest) Reset() {
	*x = SendRentalConfirmationRequest{}
	mi := &file_api_proto_shop_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRentalConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRentalConfirmationRequest) ProtoMessage() {}

func (x *SendRentalConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shop_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRentalConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendRentalConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shop_proto_rawDescGZIP(), []int{19}
}

func (x *SendRentalConfirmationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendRentalConfirmationRequest) GetRentalId() string {
	if x != nil {
		return x.RentalId
	}
	return ""
}

var File_api_proto_shop_proto protoreflect.FileDescriptor

const file_api_proto_shop_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/shop.proto\x12\x04shop\"\a\n" +
	"\x05Empty\"u\n" +
	"\aBicycle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\"\x15\n" +
	"\x13ListBicyclesRequest\"A\n" +
	"\x14ListBicyclesResponse\x12)\n" +
	"\bbicycles\x18\x01 \x03(\v2\r.shop.BicycleR\bbicycles\"#\n" +
	"\x11GetBicycleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x15SearchBicyclesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x88\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"bicycle_id\x18\x03 \x01(\tR\tbicycleId\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x9c\x01\n" +
	"\x12CreateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"bicycle_id\x18\x03 \x01(\tR\tbicycleId\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x12ListOrdersResponse\x12#\n" +
	"\x06orders\x18\x01 \x03(\v2\v.shop.OrderR\x06orders\"\xc3\x01\n" +
	"\x06Rental\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"bicycle_id\x18\x03 \x01(\tR\tbicycleId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xa8\x01\n" +
	"\x13CreateRentalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"bicycle_id\x18\x02 \x01(\tR\tbicycleId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\"\"\n" +
	"\x10GetRentalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10EndRentalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x12ListRentalsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x13ListRentalsResponse\x12&\n" +
	"\arentals\x18\x01 \x03(\v2\f.shop.RentalR\arentals\"O\n" +
	"\x1cSendOrderConfirmationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"R\n" +
	"\x1dSendRentalConfirmationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\trental_id\x18\x02 \x01(\tR\brentalId2\xaa\x06\n" +
	"\vShopService\x12E\n" +
	"\fListBicycles\x12\x19.shop.ListBicyclesRequest\x1a\x1a.shop.ListBicyclesResponse\x124\n" +
	"\n" +
	"GetBicycle\x12\x17.shop.GetBicycleRequest\x1a\r.shop.Bicycle\x12I\n" +
	"\x0eSearchBicycles\x12\x1b.shop.SearchBicyclesRequest\x1a\x1a.shop.ListBicyclesResponse\x124\n" +
	"\vCreateOrder\x12\x18.shop.CreateOrderRequest\x1a\v.shop.Order\x12.\n" +
	"\bGetOrder\x12\x15.shop.GetOrderRequest\x1a\v.shop.Order\x124\n" +
	"\vCancelOrder\x12\x18.shop.CancelOrderRequest\x1a\v.shop.Empty\x12?\n" +
	"\n" +
	"ListOrders\x12\x17.shop.ListOrdersRequest\x1a\x18.shop.ListOrdersResponse\x127\n" +
	"\fCreateRental\x12\x19.shop.CreateRentalRequest\x1a\f.shop.Rental\x121\n" +
	"\tGetRental\x12\x16.shop.GetRentalRequest\x1a\f.shop.Rental\x120\n" +
	"\tEndRental\x12\x16.shop.EndRentalRequest\x1a\v.shop.Empty\x12B\n" +
	"\vListRentals\x12\x18.shop.ListRentalsRequest\x1a\x19.shop.ListRentalsResponse\x12H\n" +
	"\x15SendOrderConfirmation\x12\".shop.SendOrderConfirmationRequest\x1a\v.shop.Empty\x12J\n" +
	"\x16SendRentalConfirmation\x12#.shop.SendRentalConfirmationRequest\x1a\v.shop.EmptyB\rZ\v./api/protob\x06proto3"

var (
	file_api_proto_shop_proto_rawDescOnce sync.Once
	file_api_proto_shop_proto_rawDescData []byte
)

func file_api_proto_shop_proto_rawDescGZIP() []byte {
	file_api_proto_shop_proto_rawDescOnce.Do(func() {
		file_api_proto_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_shop_proto_rawDesc), len(file_api_proto_shop_proto_rawDesc)))
	})
	return file_api_proto_shop_proto_rawDescData
}

var file_api_proto_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_shop_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: shop.Empty
	(*Bicycle)(nil),                       // 1: shop.Bicycle
	(*ListBicyclesRequest)(nil),           // 2: shop.ListBicyclesRequest
	(*ListBicyclesResponse)(nil),          // 3: shop.ListBicyclesResponse
	(*GetBicycleRequest)(nil),             // 4: shop.GetBicycleRequest
	(*SearchBicyclesRequest)(nil),         // 5: shop.SearchBicyclesRequest
	(*Order)(nil),                         // 6: shop.Order
	(*CreateOrderRequest)(nil),            // 7: shop.CreateOrderRequest
	(*GetOrderRequest)(nil),               // 8: shop.GetOrderRequest
	(*CancelOrderRequest)(nil),            // 9: shop.CancelOrderRequest
	(*ListOrdersRequest)(nil),             // 10: shop.ListOrdersRequest
	(*ListOrdersResponse)(nil),            // 11: shop.ListOrdersResponse
	(*Rental)(nil),                        // 12: shop.Rental
	(*CreateRentalRequest)(nil),           // 13: shop.CreateRentalRequest
	(*GetRentalRequest)(nil),              // 14: shop.GetRentalRequest
	(*EndRentalRequest)(nil),              // 15: shop.EndRentalRequest
	(*ListRentalsRequest)(nil),            // 16: shop.ListRentalsRequest
	(*ListRentalsResponse)(nil),           // 17: shop.ListRentalsResponse
	(*SendOrderConfirmationRequest)(nil),  // 18: shop.SendOrderConfirmationRequest
	(*SendRentalConfirmationRequest)(nil), // 19: shop.SendRentalConfirmationRequest
}
var file_api_proto_shop_proto_depIdxs = []int32{
	1,  // 0: shop.ListBicyclesResponse.bicycles:type_name -> shop.Bicycle
	6,  // 1: shop.ListOrdersResponse.orders:type_name -> shop.Order
	12, // 2: shop.ListRentalsResponse.rentals:type_name -> shop.Rental
	2,  // 3: shop.ShopService.ListBicycles:input_type -> shop.ListBicyclesRequest
	4,  // 4: shop.ShopService.GetBicycle:input_type -> shop.GetBicycleRequest
	5,  // 5: shop.ShopService.SearchBicycles:input_type -> shop.SearchBicyclesRequest
	7,  // 6: shop.ShopService.CreateOrder:input_type -> shop.CreateOrderRequest
	8,  // 7: shop.ShopService.GetOrder:input_type -> shop.GetOrderRequest
	9,  // 8: shop.ShopService.CancelOrder:input_type -> shop.CancelOrderRequest
	10, // 9: shop.ShopService.ListOrders:input_type -> shop.ListOrdersRequest
	13, // 10: shop.ShopService.CreateRental:input_type -> shop.CreateRentalRequest
	14, // 11: shop.ShopService.GetRental:input_type -> shop.GetRentalRequest
	15, // 12: shop.ShopService.EndRental:input_type -> shop.EndRentalRequest
	16, // 13: shop.ShopService.ListRentals:input_type -> shop.ListRentalsRequest
	18, // 14: shop.ShopService.SendOrderConfirmation:input_type -> shop.SendOrderConfirmationRequest
	19, // 15: shop.ShopService.SendRentalConfirmation:input_type -> shop.SendRentalConfirmationRequest
	3,  // 16: shop.ShopService.ListBicycles:output_type -> shop.ListBicyclesResponse
	1,  // 17: shop.ShopService.GetBicycle:output_type -> shop.Bicycle
	3,  // 18: shop.ShopService.SearchBicycles:output_type -> shop.ListBicyclesResponse
	6,  // 19: shop.ShopService.CreateOrder:output_type -> shop.Order
	6,  // 20: shop.ShopService.GetOrder:output_type -> shop.Order
	0,  // 21: shop.ShopService.CancelOrder:output_type -> shop.Empty
	11, // 22: shop.ShopService.ListOrders:output_type -> shop.ListOrdersResponse
	12, // 23: shop.ShopService.CreateRental:output_type -> shop.Rental
	12, // 24: shop.ShopService.GetRental:output_type -> shop.Rental
	0,  // 25: shop.ShopService.EndRental:output_type -> shop.Empty
	17, // 26: shop.ShopService.ListRentals:output_type -> shop.ListRentalsResponse
	0,  // 27: shop.ShopService.SendOrderConfirmation:output_type -> shop.Empty
	0,  // 28: shop.ShopService.SendRentalConfirmation:output_type -> shop.Empty
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_shop_proto_init() }
func file_api_proto_shop_proto_init() {
	if File_api_proto_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_shop_proto_rawDesc), len(file_api_proto_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_shop_proto_goTypes,
		DependencyIndexes: file_api_proto_shop_proto_depIdxs,
		MessageInfos:      file_api_proto_shop_proto_msgTypes,
	}.Build()
	File_api_proto_shop_proto = out.File
	file_api_proto_shop_proto_goTypes = nil
	file_api_proto_shop_proto_depIdxs = nil
}
